# Generated by Django 2.1.7 on 2019-03-28 13:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=64)),
                ('producer_id', models.CharField(max_length=64)),
                ('limit', models.CharField(max_length=10)),
                ('temp_min', models.IntegerField()),
                ('temp_max', models.IntegerField()),
                ('hum_min', models.IntegerField()),
                ('hum_max', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('SLA', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTask',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description', models.CharField(max_length=32)),
                ('task_type', models.PositiveSmallIntegerField(choices=[(0, 'Entrada'), (1, 'Intern'), (2, 'Sortida')], default=1, validators=[django.core.validators.MaxValueValidator(2)])),
                ('task_status', models.PositiveSmallIntegerField(choices=[(0, "Pendent d'assignació"), (1, 'Assignada automaticament'), (2, 'Assignada manualment'), (3, 'Rebuda'), (4, 'Completada')], default=0, validators=[django.core.validators.MaxValueValidator(4)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('containers', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='magatzem.Container')),
            ],
            options={
                'verbose_name': 'historical task',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nova Sala', max_length=16)),
                ('temp_min', models.SmallIntegerField()),
                ('temp_max', models.SmallIntegerField()),
                ('hum_min', models.PositiveSmallIntegerField()),
                ('hum_max', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('limit', models.PositiveIntegerField()),
                ('room_status', models.PositiveSmallIntegerField(choices=[(0, 'Tancada'), (1, 'Oberta')], default=0, validators=[django.core.validators.MaxValueValidator(1)])),
            ],
            options={
                'ordering': ['-room_status', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=32)),
                ('task_type', models.PositiveSmallIntegerField(choices=[(0, 'Entrada'), (1, 'Intern'), (2, 'Sortida')], default=1, validators=[django.core.validators.MaxValueValidator(2)])),
                ('task_status', models.PositiveSmallIntegerField(choices=[(0, "Pendent d'assignació"), (1, 'Assignada automaticament'), (2, 'Assignada manualment'), (3, 'Rebuda'), (4, 'Completada')], default=0, validators=[django.core.validators.MaxValueValidator(4)])),
                ('containers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magatzem.Container')),
                ('destination_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='magatzem.Room')),
                ('origin_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='magatzem.Room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='destination_room',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='magatzem.Room'),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='origin_room',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='magatzem.Room'),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='container',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magatzem.Room'),
        ),
    ]
