# Generated by Django 2.1.7 on 2019-04-08 22:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import magatzem.models.container
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=64, validators=[magatzem.models.container.validate_products])),
                ('producer_id', models.CharField(max_length=64, validators=[magatzem.models.container.validate_client])),
                ('limit', models.CharField(max_length=10, validators=[magatzem.models.container.validate_limit])),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('temp_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(-999), django.core.validators.MaxValueValidator(999)])),
                ('temp_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(-999), django.core.validators.MaxValueValidator(999)])),
                ('hum_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hum_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('SLA', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalRoom',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(default='Nova Sala', max_length=16, verbose_name='Nom')),
                ('temp_min', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Temperatura mínima (ºC)')),
                ('temp_max', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Temperatura màxima (ºC)')),
                ('hum_min', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Humitat mínima (%)')),
                ('hum_max', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Humitat màxima (%)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Espai ocupat')),
                ('limit', models.PositiveIntegerField(verbose_name='Capacitat màxima')),
                ('room_status', models.PositiveSmallIntegerField(choices=[(0, 'Tancada'), (1, 'Oberta')], default=0, validators=[django.core.validators.MaxValueValidator(1)], verbose_name='Estat')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical room',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTask',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description', models.CharField(max_length=32, verbose_name='Descripció')),
                ('task_type', models.PositiveSmallIntegerField(choices=[(0, "Moviment d' Entrada"), (1, 'Moviment Intern'), (2, 'Moviment de Sortida')], default=1, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Tipus')),
                ('task_status', models.PositiveSmallIntegerField(choices=[(0, "Pendent d'assignació"), (1, 'Assignada automaticament'), (2, 'Assignada manualment'), (3, 'Rebuda'), (4, 'Completada')], default=0, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Estat')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('containers', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='magatzem.Container', verbose_name='Contenidor')),
            ],
            options={
                'verbose_name': 'historical task',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nova Sala', max_length=16, verbose_name='Nom')),
                ('temp_min', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Temperatura mínima (ºC)')),
                ('temp_max', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Temperatura màxima (ºC)')),
                ('hum_min', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Humitat mínima (%)')),
                ('hum_max', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Humitat màxima (%)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Espai ocupat')),
                ('limit', models.PositiveIntegerField(verbose_name='Capacitat màxima')),
                ('room_status', models.PositiveSmallIntegerField(choices=[(0, 'Tancada'), (1, 'Oberta')], default=0, validators=[django.core.validators.MaxValueValidator(1)], verbose_name='Estat')),
            ],
            options={
                'ordering': ['-room_status', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=32, verbose_name='Descripció')),
                ('task_type', models.PositiveSmallIntegerField(choices=[(0, "Moviment d' Entrada"), (1, 'Moviment Intern'), (2, 'Moviment de Sortida')], default=1, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Tipus')),
                ('task_status', models.PositiveSmallIntegerField(choices=[(0, "Pendent d'assignació"), (1, 'Assignada automaticament'), (2, 'Assignada manualment'), (3, 'Rebuda'), (4, 'Completada')], default=0, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Estat')),
                ('containers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='magatzem.Container', verbose_name='Contenidor')),
                ('destination_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='magatzem.Room', verbose_name='Sala destí')),
                ('origin_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='magatzem.Room', verbose_name="Sala d'origen")),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Persona assignada')),
            ],
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='destination_room',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='magatzem.Room', verbose_name='Sala destí'),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='origin_room',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='magatzem.Room', verbose_name="Sala d'origen"),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Persona assignada'),
        ),
        migrations.AddField(
            model_name='container',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magatzem.Room'),
        ),
    ]
