# Generated by Django 2.1.7 on 2019-04-26 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magatzem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltask',
            name='containers',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='destination_room',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='origin_room',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='HistoricalTask',
        ),
    ]
